pipeline {
    environment {
        MYSQL_ROOT_PASSWORD=credentials("MYSQL_ROOT_PASSWORD")
    }
    agent any
    stages {
        Stage('Run Script') {
            steps{
                dir("Task2"){
                    sh "sh deploy.sh"
                }
                
            }
        }
    }
}